"""Contract tests pinning generated agent tool schemas (T018, T027, T041).

The tools generated by the implementation must match
contracts/agent-tools.md and weekly-plan.schema.json — schema, strictness,
result shapes, and validator error codes. Drift is a failing test.
"""

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest
from test_plan_schema import contract_schema, normalize, sample_payload

from sous_chef.agent.client import SERVER_TOOLS
from sous_chef.agent.session import Session
from sous_chef.agent.tools import build_tools
from sous_chef.services.history_repo import HistoryRepo
from sous_chef.services.plan_validator import ERROR_CODES

# A moment inside 2026-W30, the week sample_payload() plans for.
FIXED_NOW = datetime(2026, 7, 22, 12, 0, tzinfo=UTC)

# The full error-code table from contracts/agent-tools.md (propose_plan section).
CONTRACT_ERROR_CODES = frozenset(
    {
        "dinner_count_out_of_range",
        "lunch_count_out_of_range",
        "meal_count_mismatch",
        "batch_meal_count",
        "stretch_meal_count",
        "batch_stretch_same_meal",
        "batch_coverage_mismatch",
        "technique_not_new",
        "repeated_dish",
        "missing_field",
        "invalid_value",
    }
)

# Codes owned by the US1 deterministic validators (history rules arrive with US4).
US1_ERROR_CODES = CONTRACT_ERROR_CODES - {"technique_not_new", "repeated_dish"}


class _UnusedTransport:
    async def run_turn(self, **_kwargs: Any) -> Any:
        raise AssertionError("contract tests never run the transport")


@pytest.fixture
def session(tmp_path: Path) -> Session:
    return Session(
        chat_id=1,
        transport=_UnusedTransport(),
        repo=HistoryRepo(tmp_path / "contract.db"),
        system_prompt="contract-test prompt",
        tool_factory=build_tools,
        tz=UTC,
        now=lambda: FIXED_NOW,
    )


def tool_named(session: Session, name: str) -> Any:
    tools = {tool.name: tool for tool in build_tools(session)}
    assert name in tools, f"expected a {name} tool, got {sorted(tools)}"
    return tools[name]


class TestProposePlanSchema:
    def test_input_schema_matches_weekly_plan_contract(self, session: Session) -> None:
        tool = tool_named(session, "propose_plan")
        assert normalize(tool.to_dict()["input_schema"]) == normalize(contract_schema())

    def test_declared_strict(self, session: Session) -> None:
        assert tool_named(session, "propose_plan").to_dict()["strict"] is True

    def test_has_description(self, session: Session) -> None:
        assert tool_named(session, "propose_plan").to_dict()["description"]

    def test_validator_codes_pinned_to_contract(self) -> None:
        assert ERROR_CODES <= CONTRACT_ERROR_CODES
        assert US1_ERROR_CODES <= ERROR_CODES


class TestProposePlanResultShape:
    async def test_valid_plan_result(self, session: Session) -> None:
        tool = tool_named(session, "propose_plan")
        result = json.loads(await tool.call(sample_payload()))
        assert result["ok"] is True
        assert result["staged"] is True
        assert isinstance(result["estimated_bill_usd"], float)
        assert result["budget_delta_usd"] is None
        assert isinstance(result["grocery_item_count"], int)

    async def test_invalid_plan_result_carries_error_codes(
        self, session: Session
    ) -> None:
        payload = sample_payload()
        payload["dinner_count"] = 5
        tool = tool_named(session, "propose_plan")
        result = json.loads(await tool.call(payload))
        assert result["ok"] is False
        assert result["staged"] is False
        codes = {error["code"] for error in result["errors"]}
        assert codes, "expected at least one error"
        assert codes <= CONTRACT_ERROR_CODES
        for error in result["errors"]:
            assert error["message"]


class TestServerWebSearchTool:
    def test_declared_per_contract(self) -> None:
        assert {
            "type": "web_search_20260209",
            "name": "web_search",
            "max_uses": 5,
        } in SERVER_TOOLS


# The accept_plan input schema from contracts/agent-tools.md, structurally.
ACCEPT_PLAN_CONTRACT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {"week_id": {"type": "string"}},
    "required": ["week_id"],
}


async def stage_draft(session: Session, payload: dict[str, Any]) -> None:
    result = json.loads(await tool_named(session, "propose_plan").call(payload))
    assert result["ok"] is True, f"fixture plan must stage cleanly: {result}"


class TestAcceptPlanSchema:
    def test_input_schema_matches_contract(self, session: Session) -> None:
        tool = tool_named(session, "accept_plan")
        assert normalize(tool.to_dict()["input_schema"]) == normalize(
            ACCEPT_PLAN_CONTRACT_SCHEMA
        )

    def test_has_description(self, session: Session) -> None:
        assert tool_named(session, "accept_plan").to_dict()["description"]


class TestAcceptPlanResultShape:
    async def test_accept_returns_grocery_list_and_meals_logged(
        self, session: Session
    ) -> None:
        await stage_draft(session, sample_payload())
        tool = tool_named(session, "accept_plan")
        result = json.loads(await tool.call({"week_id": "2026-W30"}))

        assert result["ok"] is True
        assert result["week_id"] == "2026-W30"
        assert result["meals_logged"] == 3
        grocery = result["grocery_list"]
        assert isinstance(grocery["items"], list) and grocery["items"]
        for item in grocery["items"]:
            assert item["name"]
            assert item["quantities"], "every item carries at least one quantity"
            for quantity in item["quantities"]:
                assert set(quantity) == {"amount", "unit"}
            assert isinstance(item["estimated_price_usd"], float)
        assert isinstance(grocery["estimated_total_usd"], float)
        assert grocery["budget_delta_usd"] is None

    async def test_no_staged_draft_error(self, session: Session) -> None:
        tool = tool_named(session, "accept_plan")
        result = json.loads(await tool.call({"week_id": "2026-W30"}))
        assert result["ok"] is False
        assert [error["code"] for error in result["errors"]] == ["no_staged_draft"]
        assert result["errors"][0]["message"]

    async def test_week_mismatch_error(self, session: Session) -> None:
        await stage_draft(session, sample_payload())
        tool = tool_named(session, "accept_plan")
        result = json.loads(await tool.call({"week_id": "2026-W31"}))
        assert result["ok"] is False
        assert [error["code"] for error in result["errors"]] == ["week_mismatch"]

    async def test_week_already_final_error(self, session: Session) -> None:
        past_week_payload = sample_payload() | {"week_id": "2026-W29"}
        await stage_draft(session, past_week_payload)
        tool = tool_named(session, "accept_plan")
        result = json.loads(await tool.call({"week_id": "2026-W29"}))
        assert result["ok"] is False
        assert [error["code"] for error in result["errors"]] == ["week_already_final"]


def canon(schema: dict[str, Any]) -> Any:
    """normalize() plus 'no required key means required: []'."""
    out = normalize(schema)
    out.setdefault("required", [])
    return out


# The get_meal_history input schema from contracts/agent-tools.md.
GET_MEAL_HISTORY_CONTRACT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {"weeks_back": {"type": "integer", "default": 8}},
    "required": [],
}

# The record_cooked_checkin input schema from contracts/agent-tools.md.
RECORD_COOKED_CHECKIN_CONTRACT_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "week_id": {"type": "string"},
        "cooked_meal_names": {
            "type": "array",
            "items": {"type": "string"},
            "default": [],
        },
        "user_skipped_checkin": {"type": "boolean", "default": False},
    },
    "required": ["week_id"],
}


async def accept_week(session: Session, week_id: str) -> None:
    await stage_draft(session, sample_payload() | {"week_id": week_id})
    result = json.loads(
        await tool_named(session, "accept_plan").call({"week_id": week_id})
    )
    assert result["ok"] is True, f"fixture week must accept cleanly: {result}"


@pytest.fixture
def past_week_session(tmp_path: Path) -> tuple[Session, Session]:
    """A session in 2026-W30 and one in 2026-W29, sharing one repo."""
    repo = HistoryRepo(tmp_path / "contract-history.db")

    def session_at(moment: datetime) -> Session:
        return Session(
            chat_id=1,
            transport=_UnusedTransport(),
            repo=repo,
            system_prompt="contract-test prompt",
            tool_factory=build_tools,
            tz=UTC,
            now=lambda: moment,
        )

    in_w29 = session_at(datetime(2026, 7, 15, 12, 0, tzinfo=UTC))
    current = session_at(FIXED_NOW)
    return current, in_w29


class TestGetMealHistorySchema:
    def test_input_schema_matches_contract(self, session: Session) -> None:
        tool = tool_named(session, "get_meal_history")
        assert canon(tool.to_dict()["input_schema"]) == canon(
            GET_MEAL_HISTORY_CONTRACT_SCHEMA
        )

    def test_has_description(self, session: Session) -> None:
        assert tool_named(session, "get_meal_history").to_dict()["description"]


class TestGetMealHistoryResultShape:
    async def test_first_ever_session_result(self, session: Session) -> None:
        tool = tool_named(session, "get_meal_history")
        result = json.loads(await tool.call({}))
        assert result["ok"] is True
        assert result["current_week_id"] == "2026-W30"
        assert result["pending_checkin_week_id"] is None
        assert result["cooked_dish_names_last_4_weeks"] == []
        assert result["known_techniques"] == []
        assert result["weeks"] == []

    async def test_result_with_history(self, past_week_session: Any) -> None:
        current, in_w29 = past_week_session
        await accept_week(in_w29, "2026-W29")

        tool = tool_named(current, "get_meal_history")
        result = json.loads(await tool.call({"weeks_back": 4}))
        assert result["ok"] is True
        assert result["current_week_id"] == "2026-W30"
        assert result["pending_checkin_week_id"] == "2026-W29"
        (week,) = result["weeks"]
        assert week["week_id"] == "2026-W29"
        assert week["status"] == "final", "past weeks finalize lazily on lookup"
        assert {meal["name"] for meal in week["meals"]} == {
            "Chicken chili",
            "Seared salmon",
            "Turkey stir-fry",
        }
        for meal in week["meals"]:
            assert set(meal) == {
                "name",
                "is_batch",
                "is_stretch",
                "technique",
                "cooked_status",
            }
            assert meal["cooked_status"] == "planned"


class TestRecordCookedCheckinSchema:
    def test_input_schema_matches_contract(self, session: Session) -> None:
        tool = tool_named(session, "record_cooked_checkin")
        assert canon(tool.to_dict()["input_schema"]) == canon(
            RECORD_COOKED_CHECKIN_CONTRACT_SCHEMA
        )

    def test_has_description(self, session: Session) -> None:
        assert tool_named(session, "record_cooked_checkin").to_dict()["description"]


class TestRecordCookedCheckinResultShape:
    async def test_partial_checkin_records_cooked_and_skipped(
        self, past_week_session: Any
    ) -> None:
        current, in_w29 = past_week_session
        await accept_week(in_w29, "2026-W29")
        tool = tool_named(current, "record_cooked_checkin")
        result = json.loads(
            await tool.call(
                {"week_id": "2026-W29", "cooked_meal_names": ["Chicken chili"]}
            )
        )
        assert result["ok"] is True
        assert result["recorded"]["cooked"] == ["Chicken chili"]
        assert sorted(result["recorded"]["skipped"]) == [
            "Seared salmon",
            "Turkey stir-fry",
        ]

    async def test_user_skipped_checkin_marks_all_cooked(
        self, past_week_session: Any
    ) -> None:
        current, in_w29 = past_week_session
        await accept_week(in_w29, "2026-W29")
        tool = tool_named(current, "record_cooked_checkin")
        result = json.loads(
            await tool.call({"week_id": "2026-W29", "user_skipped_checkin": True})
        )
        assert result["ok"] is True
        assert sorted(result["recorded"]["cooked"]) == [
            "Chicken chili",
            "Seared salmon",
            "Turkey stir-fry",
        ]
        assert result["recorded"]["skipped"] == []

    async def test_unknown_week_error(self, session: Session) -> None:
        tool = tool_named(session, "record_cooked_checkin")
        result = json.loads(await tool.call({"week_id": "2020-W01"}))
        assert result["ok"] is False
        assert [error["code"] for error in result["errors"]] == ["unknown_week"]

    async def test_unknown_meal_name_error(self, past_week_session: Any) -> None:
        current, in_w29 = past_week_session
        await accept_week(in_w29, "2026-W29")
        tool = tool_named(current, "record_cooked_checkin")
        result = json.loads(
            await tool.call(
                {"week_id": "2026-W29", "cooked_meal_names": ["Beef wellington"]}
            )
        )
        assert result["ok"] is False
        assert [error["code"] for error in result["errors"]] == ["unknown_meal_name"]

    async def test_already_recorded_error(self, past_week_session: Any) -> None:
        current, in_w29 = past_week_session
        await accept_week(in_w29, "2026-W29")
        tool = tool_named(current, "record_cooked_checkin")
        first = json.loads(
            await tool.call({"week_id": "2026-W29", "user_skipped_checkin": True})
        )
        assert first["ok"] is True
        again = json.loads(
            await tool.call({"week_id": "2026-W29", "user_skipped_checkin": True})
        )
        assert again["ok"] is False
        assert [error["code"] for error in again["errors"]] == ["already_recorded"]
