"""Contract tests pinning generated agent tool schemas (T018).

The propose_plan tool generated by the implementation must match
contracts/agent-tools.md and weekly-plan.schema.json — schema, strictness,
result shape, and validator error codes. Drift is a failing test.
"""

import json
from pathlib import Path
from typing import Any

import pytest
from test_plan_schema import contract_schema, normalize, sample_payload

from sous_chef.agent.client import SERVER_TOOLS
from sous_chef.agent.session import Session
from sous_chef.agent.tools import build_tools
from sous_chef.services.history_repo import HistoryRepo
from sous_chef.services.plan_validator import ERROR_CODES

# The full error-code table from contracts/agent-tools.md (propose_plan section).
CONTRACT_ERROR_CODES = frozenset(
    {
        "dinner_count_out_of_range",
        "lunch_count_out_of_range",
        "meal_count_mismatch",
        "batch_meal_count",
        "stretch_meal_count",
        "batch_stretch_same_meal",
        "batch_coverage_mismatch",
        "technique_not_new",
        "repeated_dish",
        "missing_field",
        "invalid_value",
    }
)

# Codes owned by the US1 deterministic validators (history rules arrive with US4).
US1_ERROR_CODES = CONTRACT_ERROR_CODES - {"technique_not_new", "repeated_dish"}


class _UnusedTransport:
    async def run_turn(self, **_kwargs: Any) -> Any:
        raise AssertionError("contract tests never run the transport")


@pytest.fixture
def session(tmp_path: Path) -> Session:
    return Session(
        chat_id=1,
        transport=_UnusedTransport(),
        repo=HistoryRepo(tmp_path / "contract.db"),
        system_prompt="contract-test prompt",
        tool_factory=build_tools,
    )


def tool_named(session: Session, name: str) -> Any:
    tools = {tool.name: tool for tool in build_tools(session)}
    assert name in tools, f"expected a {name} tool, got {sorted(tools)}"
    return tools[name]


class TestProposePlanSchema:
    def test_input_schema_matches_weekly_plan_contract(self, session: Session) -> None:
        tool = tool_named(session, "propose_plan")
        assert normalize(tool.to_dict()["input_schema"]) == normalize(contract_schema())

    def test_declared_strict(self, session: Session) -> None:
        assert tool_named(session, "propose_plan").to_dict()["strict"] is True

    def test_has_description(self, session: Session) -> None:
        assert tool_named(session, "propose_plan").to_dict()["description"]

    def test_validator_codes_pinned_to_contract(self) -> None:
        assert ERROR_CODES <= CONTRACT_ERROR_CODES
        assert US1_ERROR_CODES <= ERROR_CODES


class TestProposePlanResultShape:
    async def test_valid_plan_result(self, session: Session) -> None:
        tool = tool_named(session, "propose_plan")
        result = json.loads(await tool.call(sample_payload()))
        assert result["ok"] is True
        assert result["staged"] is True
        assert isinstance(result["estimated_bill_usd"], float)
        assert result["budget_delta_usd"] is None
        assert isinstance(result["grocery_item_count"], int)

    async def test_invalid_plan_result_carries_error_codes(
        self, session: Session
    ) -> None:
        payload = sample_payload()
        payload["dinner_count"] = 5
        tool = tool_named(session, "propose_plan")
        result = json.loads(await tool.call(payload))
        assert result["ok"] is False
        assert result["staged"] is False
        codes = {error["code"] for error in result["errors"]}
        assert codes, "expected at least one error"
        assert codes <= CONTRACT_ERROR_CODES
        for error in result["errors"]:
            assert error["message"]


class TestServerWebSearchTool:
    def test_declared_per_contract(self) -> None:
        assert {
            "type": "web_search_20260209",
            "name": "web_search",
            "max_uses": 5,
        } in SERVER_TOOLS
