"""Deterministic grocery merging and bill totaling.

Every quantity and total is computed from the plan's structured
ingredients — never generated by the model — so the math is provable by the
unit tests. Names are normalized (casefold, trim, simple-plural
singularize); quantities merge within a unit family (weight, volume, or
count) and the merged total picks its own display unit off a customary
ladder, so the list never depends on which meal listed the ingredient
first. Cross-family quantities render as a compound quantity on one line.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from sous_chef.models.grocery import GroceryItem, GroceryList, PackageCount, Quantity
from sous_chef.models.plan import Ingredient, Package, Unit, WeeklyPlan

_OUNCES_PER_UNIT = {
    Unit.OZ: 1.0,
    Unit.LB: 16.0,
}

_TEASPOONS_PER_UNIT = {
    Unit.TSP: 1.0,
    Unit.TBSP: 3.0,
    Unit.FL_OZ: 6.0,
    Unit.CUP: 48.0,
    Unit.PINT: 96.0,
    Unit.QUART: 192.0,
    Unit.GALLON: 768.0,
}

WEIGHT = "weight"
VOLUME = "volume"

# The units a merged total may be *displayed* in, largest first. `pint` is
# accepted as input but never chosen: a cook reads cups.
_DISPLAY_LADDERS: dict[str, tuple[Unit, ...]] = {
    WEIGHT: (Unit.LB, Unit.OZ),
    VOLUME: (
        Unit.GALLON,
        Unit.QUART,
        Unit.CUP,
        Unit.FL_OZ,
        Unit.TBSP,
        Unit.TSP,
    ),
}

_SIBILANT_ENDINGS = ("ss", "x", "z", "ch", "sh")
_VOWELS = "aeiou"


def normalize_ingredient_name(name: str) -> str:
    """Casefold, trim, collapse whitespace, and singularize simple plurals."""
    words = name.casefold().split()
    return " ".join(_singularize(word) for word in words)


def pluralize_ingredient_name(name: str) -> str:
    """Pluralize the last word, so '3 count yellow onion' reads '3 yellow onions'."""
    words = name.split()
    if not words:
        return name
    words[-1] = _pluralize(words[-1])
    return " ".join(words)


def _singularize(word: str) -> str:
    if len(word) > 3 and word.endswith("ies"):
        return word[:-3] + "y"
    if len(word) > 3 and word.endswith("oes"):
        return word[:-2]
    if len(word) > 2 and word.endswith("s") and not word.endswith("ss"):
        return word[:-1]
    return word


def _pluralize(word: str) -> str:
    # A trailing lone 's' means the model already wrote the plural.
    if word.endswith("s") and not word.endswith("ss"):
        return word
    if word.endswith(_SIBILANT_ENDINGS):
        return word + "es"
    if word.endswith("y") and len(word) > 1 and word[-2] not in _VOWELS:
        return word[:-1] + "ies"
    if word.endswith("o"):
        return word + "es"
    return word + "s"


def _unit_family(unit: Unit) -> str:
    if unit in _OUNCES_PER_UNIT:
        return WEIGHT
    if unit in _TEASPOONS_PER_UNIT:
        return VOLUME
    # Countable things merge only with themselves and have no ladder.
    return unit.value


def _base_factor(unit: Unit) -> float:
    return _OUNCES_PER_UNIT.get(unit) or _TEASPOONS_PER_UNIT.get(unit) or 1.0


def _display_unit(family: str, base_amount: float) -> Unit:
    """The largest ladder unit the total fills, or the smallest one."""
    ladder = _DISPLAY_LADDERS.get(family)
    if ladder is None:
        return Unit(family)
    for unit in ladder:
        if base_amount >= _base_factor(unit):
            return unit
    return ladder[-1]


@dataclass
class _Bucket:
    """One mergeable quantity group: a unit family for one ingredient."""

    family: str
    base_amount: float = 0.0
    # A package pins the display to the unit its size is quoted in, so
    # '3 x 15 oz can' is not shown next to a total in pounds.
    pinned_unit: Unit | None = None

    def add(self, quantity: float, unit: Unit) -> None:
        self.base_amount += quantity * _base_factor(unit)

    def amount_in(self, unit: Unit) -> float:
        return self.base_amount / _base_factor(unit)

    def to_quantity(self) -> Quantity:
        unit = self.pinned_unit or _display_unit(self.family, self.base_amount)
        return Quantity(amount=round(self.amount_in(unit), 2), unit=unit)


@dataclass
class _ItemAccumulator:
    display_name: str
    buckets: dict[str, _Bucket] = field(default_factory=dict)
    package: Package | None = None
    package_family: str | None = None
    price_usd: float = 0.0

    def add(self, ingredient: Ingredient) -> None:
        family = _unit_family(ingredient.unit)
        bucket = self.buckets.setdefault(family, _Bucket(family=family))
        bucket.add(ingredient.quantity, ingredient.unit)
        self.price_usd += ingredient.estimated_price_usd
        self._adopt_package(ingredient, family, bucket)

    def _adopt_package(
        self, ingredient: Ingredient, family: str, bucket: _Bucket
    ) -> None:
        """Take the first declared package, if it can be counted at all.

        A package quoted in another family (a can sized in oz against a
        quantity in cups) cannot be converted, so it is dropped rather than
        guessed at.
        """
        package = ingredient.package
        if package is None or self.package is not None:
            return
        if package.size_amount <= 0 or _unit_family(package.size_unit) != family:
            return
        self.package = package
        self.package_family = family
        bucket.pinned_unit = package.size_unit

    def to_item(self) -> GroceryItem:
        return GroceryItem(
            name=self.display_name,
            quantities=[bucket.to_quantity() for bucket in self.buckets.values()],
            package=self._package_count(),
            estimated_price_usd=round(self.price_usd, 2),
        )

    def _package_count(self) -> PackageCount | None:
        if self.package is None or self.package_family is None:
            return None
        total = self.buckets[self.package_family].amount_in(self.package.size_unit)
        # Round before ceiling: an exact multiple must not buy a spare
        # package because of float drift.
        packages = math.ceil(round(total / self.package.size_amount, 6))
        return PackageCount(
            form=self.package.form,
            size_amount=self.package.size_amount,
            size_unit=self.package.size_unit,
            packages=packages,
        )


def build_grocery_list(plan: WeeklyPlan) -> GroceryList:
    """Merge the plan's ingredients into one flat list and total the bill."""
    accumulators: dict[str, _ItemAccumulator] = {}
    for meal in plan.meals:
        for ingredient in meal.ingredients:
            key = normalize_ingredient_name(ingredient.name)
            if key not in accumulators:
                display = " ".join(ingredient.name.casefold().split())
                accumulators[key] = _ItemAccumulator(display_name=display)
            accumulators[key].add(ingredient)
    items = [accumulator.to_item() for accumulator in accumulators.values()]
    total = round(sum(item.estimated_price_usd for item in items), 2)
    budget = plan.weekly_budget_usd
    return GroceryList(
        items=items,
        estimated_total_usd=total,
        budget_delta_usd=None if budget is None else round(total - budget, 2),
    )
