"""Deterministic grocery merging and bill totaling.

Every quantity and total is computed from the plan's structured
ingredients — never generated by the model — so the math is provable
by the unit tests. Names are normalized (casefold, trim, simple-plural
singularize); quantities merge when units convert within a family (mass,
volume, count, or an identical free-form token); anything else renders as a
compound quantity on the same line.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from sous_chef.models.grocery import GroceryItem, GroceryList, Quantity
from sous_chef.models.plan import WeeklyPlan

_GRAMS_PER_UNIT = {
    "g": 1.0,
    "kg": 1000.0,
    "oz": 28.349523125,
    "lb": 453.59237,
}

_MILLILITERS_PER_UNIT = {
    "ml": 1.0,
    "l": 1000.0,
    "tsp": 4.92892159375,
    "tbsp": 14.78676478125,
    "cup": 236.5882365,
}


def normalize_ingredient_name(name: str) -> str:
    """Casefold, trim, collapse whitespace, and singularize simple plurals."""
    words = name.casefold().split()
    return " ".join(_singularize(word) for word in words)


def _singularize(word: str) -> str:
    if len(word) > 3 and word.endswith("ies"):
        return word[:-3] + "y"
    if len(word) > 3 and word.endswith("oes"):
        return word[:-2]
    if len(word) > 2 and word.endswith("s") and not word.endswith("ss"):
        return word[:-1]
    return word


def _unit_family(unit: str) -> str:
    if unit in _GRAMS_PER_UNIT:
        return "mass"
    if unit in _MILLILITERS_PER_UNIT:
        return "volume"
    # count and free-form tokens ('can', 'bunch') merge only with themselves.
    return unit


@dataclass
class _Bucket:
    """One mergeable quantity group: a unit family for one ingredient."""

    display_unit: str
    base_amount: float = 0.0

    def add(self, quantity: float, unit: str) -> None:
        self.base_amount += quantity * _base_factor(unit)

    def to_quantity(self) -> Quantity:
        amount = self.base_amount / _base_factor(self.display_unit)
        return Quantity(amount=round(amount, 2), unit=self.display_unit)


def _base_factor(unit: str) -> float:
    return _GRAMS_PER_UNIT.get(unit) or _MILLILITERS_PER_UNIT.get(unit) or 1.0


@dataclass
class _ItemAccumulator:
    display_name: str
    buckets: dict[str, _Bucket] = field(default_factory=dict)
    price_usd: float = 0.0

    def add(self, quantity: float, unit: str, price_usd: float) -> None:
        family = _unit_family(unit)
        if family not in self.buckets:
            self.buckets[family] = _Bucket(display_unit=unit)
        self.buckets[family].add(quantity, unit)
        self.price_usd += price_usd

    def to_item(self) -> GroceryItem:
        return GroceryItem(
            name=self.display_name,
            quantities=[bucket.to_quantity() for bucket in self.buckets.values()],
            estimated_price_usd=round(self.price_usd, 2),
        )


def build_grocery_list(plan: WeeklyPlan) -> GroceryList:
    """Merge the plan's ingredients into one flat list and total the bill."""
    accumulators: dict[str, _ItemAccumulator] = {}
    for meal in plan.meals:
        for ingredient in meal.ingredients:
            key = normalize_ingredient_name(ingredient.name)
            if key not in accumulators:
                display = " ".join(ingredient.name.casefold().split())
                accumulators[key] = _ItemAccumulator(display_name=display)
            accumulators[key].add(
                ingredient.quantity, ingredient.unit, ingredient.estimated_price_usd
            )
    items = [accumulator.to_item() for accumulator in accumulators.values()]
    total = round(sum(item.estimated_price_usd for item in items), 2)
    budget = plan.weekly_budget_usd
    return GroceryList(
        items=items,
        estimated_total_usd=total,
        budget_delta_usd=None if budget is None else round(total - budget, 2),
    )
